<a href="https://colab.research.google.com/github/Amelaouadni/Implementing-CNN-and-RNN-/blob/main/ANN_breast_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow

In [16]:
#packages
from sklearn import datasets
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import  StandardScaler
from sklearn.model_selection import train_test_split

In [17]:
#upload dataset 
df= datasets.load_breast_cancer()

In [18]:
#database decouvert
print(df.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [19]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [20]:
df.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [21]:
#data preparation
x=df.data
y=df.target

In [22]:
scaler= StandardScaler()
x_scaled= scaler.fit_transform(x)
x_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [23]:
x_train, x_test, y_train, y_test= train_test_split(x_scaled, y, test_size=0.2, random_state= 42)

In [24]:
print(x_train.shape, x_test.shape)

(455, 30) (114, 30)


In [25]:
#creation du reseau de neurone
model= tf.keras.models.Sequential()


In [28]:
model.add(tf.keras.layers.Dense(units=15, activation='relu',kernel_initializer='uniform', input_dim=30))

In [30]:
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid',kernel_initializer='uniform'))

In [31]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [32]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 15)                465       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 16        
Total params: 481
Trainable params: 481
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.fit(x_train, y_train, batch_size= 10, epochs= 100)

Epoch 1/100
46/46 [==============================] - 1s 1ms/step - loss: 0.6765 - binary_accuracy: 0.8336
Epoch 2/100
46/46 [==============================] - 0s 1ms/step - loss: 0.5149 - binary_accuracy: 0.9169
Epoch 3/100
46/46 [==============================] - 0s 1ms/step - loss: 0.3013 - binary_accuracy: 0.9465
Epoch 4/100
46/46 [==============================] - 0s 1ms/step - loss: 0.2139 - binary_accuracy: 0.9371
Epoch 5/100
46/46 [==============================] - 0s 1ms/step - loss: 0.1467 - binary_accuracy: 0.9837
Epoch 6/100
46/46 [==============================] - 0s 1ms/step - loss: 0.1382 - binary_accuracy: 0.9686
Epoch 7/100
46/46 [==============================] - 0s 1ms/step - loss: 0.1302 - binary_accuracy: 0.9736
Epoch 8/100
46/46 [==============================] - 0s 1ms/step - loss: 0.0824 - binary_accuracy: 0.9872
Epoch 9/100
46/46 [==============================] - 0s 1ms/step - loss: 0.1137 - binary_accuracy: 0.9733
Epoch 10/100
46/46 [==========================

In [37]:
test_loss, test_accuracy= model.evaluate(x_test, y_test)
print(f'test accuracy {test_accuracy} et test loss {test_loss}')

4/4 [==============================] - 0s 3ms/step - loss: 0.0567 - binary_accuracy: 0.9825
test accuracy 0.9824561476707458 et test loss 0.0566844716668129
